blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
        # /blog/
    path('', views.PostLV.as_view(), name='index'),
        # /blog/post/
    path('post/', views.PostLV.as_view(), name='post_index'),
        # /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
        # /blog/archive   --7
    path('archive/', views.PostAV.as_view(), name='post_archive'),
        # /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
        # /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
        # /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
        # /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

        # /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
        # /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

        # /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),

]

bookmark/urls.py
from django.urls import path
from bookmark.views import *

app_name = 'bookmark'
urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('change/', BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import UserCreateView, UserCreateDoneTV


'''
bookmark 임포트
from bookmark.views import BookmarkLV, BookmarkDV
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
'''
from django.conf.urls import url
from bookmark import views

urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    

    # class-based views (모델.py에 클래스나 함수 정의 후 불러오기)
    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'),

    # urls with view definition (모델.py 정의 없이 바로 뷰에서 흐름 입력)
    # path('bookmark/', ListView.as_view(model=Bookmark), name='index'),
    # path('bookmark/<int:pk>/', DetailView.as_view(model=Bookmark), name='detail'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookmark/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
# Create your models here.


class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    time = models.DateTimeField('Time', null=True, blank=True)
    date = models.DateField('date', default=datetime.datetime.now, null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return "%s %s" %(self.title, self.url)
        # return self.title

bookmark/views.py
from django.shortcuts import render
from bookmark.models import Bookmark
from django.views.generic import ListView, DetailView

from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

from django.shortcuts import render


# Create your views here.
# 제어 흐름 및 로직 구성


class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

bookmark/templates/bookmark/bookmark_change_list.html
{% extends 'base.html' %}
{% block title %}bookmark_change_list{% endblock %}
{% block content %}
    <h1>Bookmark Change - {{user}}</h1>
    <br>
    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr class="table-primary">
                <th>Title</th>
                <th>Url</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.url }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'bookmark:update' item.id %}">Update</a> </td>
                <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a> </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% block title %}bookmark_confirm_delete{% endblock %}
{% block content %}
    <h1>Bookmark Delete</h1>
    <br>
    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
    </form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}
{% block title %}bookmark_detail{% endblock %}
{% block content %}
<h1>{{ object.title }}</h1>
<ul>
    <li>URL: <a href="{{ object.url }}">{{ object.url }}</a> </li>
</ul>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}bookmark_form{% endblock %}
{% block content %}
    <h1>Bookmark Create/update - {{ user }}</h1>
    <p class="font-italic">This is a creation or update form for your bookmark.</p>

    {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
            {{ form.errors }}
        </div>
    {% endif %}
    <form action="." method="post" class="card pt-3">{% csrf_token %}
        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.url|add_class:"form-control" }}
            </div>
        </div>
        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>
    </form>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}
{% block title %}bookmark_list{% endblock %}
{% block content %}
<h1>Bookmark List</h1>
<br>
<ul>
    {% for bookmark in object_list %}
    <li><a href="{% url 'bookmark:detail' bookmark.id %}"></a>{{ bookmark }}</li>
    {% endfor %}

</ul>
{% endblock %}

bookmark/templates/bookmark/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail Page</title>
</head>
<body>
<div id="'container">
    <h1>{{dto.title}}</h1>
    <ul>
        <li>URL:<a href="'{{dto.url}}">{{dto.url}}</a></li>
    </ul>
</div>

</body>
</html>

bookmark/templates/bookmark/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List Page</title>
</head>
<body>
<div id="'container">
    <h1>Bookmark List</h1>
    {{urlCount}}개의 묵마크가 등록되어 있음
    <ul>
        {% for row in urlList %}
        <li><a href="='detail?url={{row.url}}"></a> </li>
        {% endfor %}
    </ul>
</div>

</body>
</html>