blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
        # /blog/
    path('', views.PostLV.as_view(), name='index'),
        # /blog/post/
    path('post/', views.PostLV.as_view(), name='post_index'),
        # /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
        # /blog/archive   --7
    path('archive/', views.PostAV.as_view(), name='post_archive'),
        # /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
        # /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
        # /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
        # /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

        # /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
        # /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

        # /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),

]

bookmark/urls.py
from django.urls import path
from bookmark.views import *

app_name = 'bookmark'
urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('change/', BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import UserCreateView, UserCreateDoneTV


'''
bookmark 임포트
from bookmark.views import BookmarkLV, BookmarkDV
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
'''
from django.conf.urls import url
from bookmark import views

urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    

    # class-based views (모델.py에 클래스나 함수 정의 후 불러오기)
    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'),

    # urls with view definition (모델.py 정의 없이 바로 뷰에서 흐름 입력)
    # path('bookmark/', ListView.as_view(model=Bookmark), name='index'),
    # path('bookmark/<int:pk>/', DetailView.as_view(model=Bookmark), name='detail'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from photo import views
app_name = 'photo'
urlpatterns = [
    #--- /photo/
    path('', views.AlbumLV.as_view(), name='index'),
    # view 직접 지정
    # path('', ListView.as_view(model=Album), name='index'),

    #--- /photo/album/ == /photo/
    path('album', views.AlbumLV.as_view(), name='album_list'),

    #--- /photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    #--- /photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete')
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}검은 고양이 까미{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">길고양이 까미</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'home' %}">home</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'photo:index' %}">Photo</a>
        </li>
        <li class="nav-item dropdown mx-1 btn btn-primary">
            <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">add</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a>
                <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
            </div>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="">Album</a>
                <a class="dropdown-item" href="">Photo</a>
            </div>
        </li>
        <li class="nav-item dropdown mx-1 btn btn-primary">
            <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Change</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'bookmark:change' %}">Bookmark</a>
                <a class="dropdown-item" href="{% url 'blog:change' %}">Post</a>
            </div>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="">Album</a>
                <a class="dropdown-item" href="">Photo</a>
            </div>
        </li>
        <li class="nav-item dropdown mx-1 btn btn-primary">
          <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
            <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
          </div>
        </li>
      </ul>

      <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
      </form>
      <ul class="navbar-nav ml-5 mr-5">
          <li class="nav-item dropdown mx-1 btn btn-primary">
              {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                </div>
              {% else %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;Anonymous&ensp;
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                </div>
              {% endif %}
          </li>
      </ul>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}까미 고양이{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
background-image: url("{% static 'img/compotable.jpg' %}");
background-repeat: no-repeat;
background-position: center;
background-size: 100%;
height: 500px;
border-top: 10px solid #ccc;
ppadding: 20px 0 0 20px;
}
.title {
color: #c80;
font-weight: bold;
}
.powered {
position: relative;
top: 77%;
color: #cc0;
font-style: italic;
}
</style>
{% endblock %}

{% block content %}
<div class="home-image">
    <h2 class="title">검은 고양이 까미</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i>길고양이 까미</h4>
</div>
<hr style="margin: 10px 0;">
<div class="row text-center">
    <div class="col-sm-6">
        <h3>Bookmark App</h3>
        <p> 북마크 엡 설명???? </p>
    </div>
    <div class="col-sm-6">
        <h3>Blog App</h3>
        <p> 블로그 앱 설명 ??? </p>
    </div>
</div>

{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2021 cami</div>
</footer>
{% endblock %}